# Site settings
title: TeraBackup - Dịch vụ sao lưu dữ liệu trực tuyến - Online Data Backup
email: contact@terabox.vn
description: "Dịch vụ sao lưu dữ liệu trực tuyến TeraBackup"
keywords: sao lưu dữ liệu, sao lưu trực tuyến, sao lưu doanh nghiep, sao lưu cá nhân, data backup, cloud backup, dịch vụ sao lưu
baseurl: ""
url: "http://localhost:4000"
#url: "https://www.terabox.vn"

permalink: /blog/:title/
gems:
  - jekyll-redirect-from

assets:
  js_compressor:  uglifier
  css_compressor: sass