# Site settings
title: TeraBackup - Dịch vụ sao lưu dữ liệu trực tuyến - Online Data Backup
email: contact@terabox.vn
description: "Dịch vụ sao lưu trực tuyền TeraBackup"
baseurl: ""
#url: "http://localhost:4000"
url: "http://www.terabox.vn"

# Build settings
permalink: pretty

gems:
  - jekyll-redirect-from

assets:
  js_compressor:  uglifier
  css_compressor: sass